remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  mas_url: https://apps.apple.com/ua/app/cleano/id6469460523
  tf_url: https://testflight.apple.com/join/2rV85hKb
  new_issue_url: https://github.com/deszip/Cleaner-Tracker/issues/new
