remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  tf_url: http://example.com/download.zip
  new_issue_url: https://github.com/deszip/Cleaner-Tracker/issues/new